[package]
name = "balasheet"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.40", features = ["derive"] }
clap-markdown = "0.1.5"
image = "0.25.6"
imageproc = "0.25.0"
